---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: infra
name: ai
version: 1.0.0
readme: README.md
authors:
  - Peter Grlica (github.com/petergrlica)
description: AI orchestration for infrastructure operations
license_file: LICENSE
tags:
  - aws
  - amazon
  - gcp
  - google
  - cloud
  - infrastructure
  - cluster
  - ai
dependencies:
  amazon.aws: '>=9.3.0'
  community.crypto: '>=2.17.1'
  cloud.aws_ops: '>=3.1.0'
  ansible.posix: '>=1.4.0'
  google.cloud: '>=1.3.1'
repository: https://github.com/ansible
homepage: https://www.redhat.com/en/products/ai/enterprise-linux-ai
issues: https://access.redhat.com/support/
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
