---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: infra
name: ai
version: 0.1.0
readme: README.md
authors:
  - Peter Grlica (github.com/petergrlica)
description: AI orchestration for infrastructure operations
license_file: LICENSE
tags:
  - aws
  - amazon
  - cloud
  - infrastructure
  - cluster
  - ai
dependencies:
  amazon.aws: '>=9.3.0'
  community.crypto: '>=2.17.1'
  cloud.aws_ops: '>=3.1.0'
  ansible.posix: '>=1.4.0'
repository: https://github.com/petergrlica/infra.ai
homepage: https://github.com/petergrlica/infra.ai
issues: https://github.com/petergrlica/infra.ai/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
