---
collections:
  - name: amazon.aws
    version: ">9.5.0"
  - community.crypto
  - ansible.posix
  - google.cloud
  - name: https://github.com/redhat-cop/cloud.aws_ops
    type: git
    version: 3.2.0
  - name: https://github.com/redhat-cop/cloud.azure_ops
    type: git
    version: main  # >5.0.0
