# aws ec2 ansible dynamic inventory plugin
plugin: amazon.aws.aws_ec2

#regions:
#  - eu-central-1

# Removed filters to include all instances
filters: {}

# keyed_groups:
#   # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable.
#   - key: tags.Environment
#     prefix: tag_Environment_
#     separator: ""
