---
- name: Teardown_infrastructure
  ansible.builtin.import_playbook: "{{ playbook_dir }}/../../../../playbooks/gcp_teardown.yml"

- name: Refresh inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
