---
- name: Teardown Google Cloud infrastructure
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Teardown infrastructure
      block:
        - name: Destroy an instance
          google.cloud.gcp_compute_instance:
            auth_kind: serviceaccount
            project: "{{ rhelai_gcp_project | default('default') }}"
            zone: "{{ rhelai_gcp_region }}-a"
            name: "{{ rhelai_gcp_resource_name }}-instance"
            service_account_file: "{{ rhelai_gcp_service_account_file }}"
            state: absent
