- name: Install dependencies
  ansible.builtin.import_tasks: deps.yml

- name: Self-signed certificates
  ansible.builtin.import_tasks: tls.yml

- name: Install podman
  ansible.builtin.import_tasks: podman.yml
