---
- name: Provision infrastructure
  # ansible.builtin.import_playbook: infra.ai.azure_provision
  ansible.builtin.import_playbook: "{{ playbook_dir }}/../../../../playbooks/azure_provision.yml"

- name: Refresh inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory

    # - name: Show all inventory hosts
    #   ansible.builtin.debug:
    #     var: groups['all']

# - name: Provision infrastructure
#   ansible.builtin.import_playbook: redhat.ai.ilab
#   vars:
#     my_registry_username: "{{ rhelai_ilab_registry_user }}"
#     my_registry_password: "{{ rhelai_ilab_registry_password }}"
#     rhelai_api_token: "{{ rhelai_ilab_api_token: }}"
