apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infra-aws-teardown
  title: RHEL AI AWS teardown
  description: This wizard will guide you on how to teardown RHEL AI on AWS
  namespace: default
  tags:
    - aap-operations
    - intermediate
    - rhel
spec:
  type: service
  parameters:
    - title: Prompts
      description: >-
        Teardown RHEL AI on AWS.
      required:
        - token
        - inventory
        - credentials
      properties:
        token:
          title: Token
          type: string
          description: Oauth2 token
          ui:field: AAPTokenField
          ui:widget: password
          ui:backstage:
            review:
              show: false
        inventory:
          title: Inventory
          description: Please enter the AWS inventory you want to use
          resource: inventories
          ui:field: AAPResourcePicker
        credentials:
          title: Credentials
          description: >-
            Select credentials for accessing the AWS.
          type: array
          ui:field: AAPResourcePicker
          resource: credentials
    - title: Survey
      description: >-
        Teardown RHEL AI on AWS.
      required: []
      properties:
        awsResourceName:
          title: AWS resource name
          description: AWS resource name, it is used to generate name for EC2 instance and other related resources.
          type: string
          default: myRHELAIInstance
        awsRegion:
          title: AWS region
          description: AWS region
          type: string
          default: us-east-1
        # awsKeyName:
        #   title: AWS SSH key name
        #   description: >-
        #     Please enter AWS SSH key name to use
        #   type: string
        #   default: rhelai-keyname
        awsEip:
          title: AWS Elastic IP
          description: >-
            Please enter AWS Elastic IP to deallocate. Leave empty to deallocate an elastic IP only if it was auto-allocated.
          type: string
          default: ""
  steps:
    - id: launch-job
      name: Launch RHEL Infra AI / Provision AWS
      action: rhaap:launch-job-template
      input:
        token: ${{ parameters.token }}
        values:
          templateID: null
          inventory: ${{ parameters.inventory  }}
          credentials: ${{ parameters.credentials }}
          extraVariables:
            rhelai_aws_resource_name: ${{ parameters.awsResourceName }}
            rhelai_aws_aws_region: ${{ parameters.awsRegion }}
            # rhelai_aws_key_name: ${{ parameters.awsKeyName }}
            rhelai_aws_eip: ${{ parameters.awsEip }}
  output:
    text:
      - title: Launch RHEL Infra AI / Provision AWS template executed successfully
        content: |
          **Job ID:** ${{ steps['launch-job'].output.data.id }}
          **Job STATUS:** ${{ steps['launch-job'].output.data.status }}
    links:
      - title: View in RH AAP
        url: ${{ steps['launch-job'].output.data.url }}
